### ISSUE TITLE
tutorials link is broken in readme

### ISSUE THREAD

**Issue by ajay-sreeram** [BoundaryML/baml-examples#22]
Trying to access tutorial link in readme, but the link throws 404.

**Comment by hellovai** [comment]
Thanks for flagging this @ajay-sreeram 

new link is: https://docs.boundaryml.com/docs/get-started/quickstart/python

**Comment by ajay-sreeram** [comment]
Thankyou @hellovai  for the reference, but this link doesn't have examples from this repo (like python-chatbot).
