### ISSUE TITLE
GoLang support

### ISSUE THREAD

**Issue by sjain93** [BoundaryML/baml-examples#24]
Hello,

I've tried your golang-openapi-starter and run into the following two issues

```bash
OPENAI_API_KEY=... npx @boundaryml/baml dev
error: unrecognized subcommand 'dev'

Usage: baml-cli <COMMAND>

For more information, try '--help'.
```
And after trying to run 
```bash
go get openapi  # you only need to run this once
go run main.go
```

I get the following errors 
```bash
❯ go get openapi                                                             ─╯
go: downloading go1.23.0 (darwin/arm64)
go: openapi@v0.0.0-00010101000000-000000000000 (replaced by ./baml_client): reading baml_client/go.mod: open /Users/sanchitjain/go/src/baml-examples/golang-openapi-starter/baml_client/go.mod: no such file or directory
```

```bash
❯ go run main.go                                                             ─╯
main.go:7:2: openapi@v0.0.0-00010101000000-000000000000: replacement directory ./baml_client does not exist
```

What's missing here, would you be able to update the README please? Moreover, how can I install baml-cli as a global dependency to use against my go project?

**Comment by sxlijin** [comment]
Hi there! Excited to hear that you're interested in this - this is actually an unreleased feature that we'll be putting out in the next day or two! We're doing final passes over it right now, and I'll circle on this when it's released :)

**Comment by sxlijin** [comment]
@sjain93 BAML 0.55.0 is out, which means you can now try out BAML from Go!

- [announcement](https://discord.com/channels/1119368998161752075/1119375433666920530/1282818005084016721)
- [quickstart docs](https://docs.boundaryml.com/docs/get-started/quickstart/openapi)
- [baml-examples for golang-openapi](https://github.com/BoundaryML/baml-examples/tree/main/golang-openapi-starter)
